/*
 * #%L
 * ImgLib2: a general-purpose, multidimensional image processing library.
 * %%
 * Copyright (C) 2009 - 2025 Tobias Pietzsch, Stephan Preibisch, Stephan Saalfeld,
 * John Bogovic, Albert Cardona, Barry DeZonia, Christian Dietz, Jan Funke,
 * Aivar Grislis, Jonathan Hale, Grant Harris, Stefan Helfrich, Mark Hiner,
 * Martin Horn, Steffen Jaensch, Lee Kamentsky, Larry Lindsey, Melissa Linkert,
 * Mark Longair, Brian Northan, Nick Perry, Curtis Rueden, Johannes Schindelin,
 * Jean-Yves Tinevez and Michael Zinsmaier.
 * %%
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 * 
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 * #L%
 */
package net.imglib2.algorithm.blocks.transform;

import net.imglib2.blocks.VolatileArray;
import net.imglib2.type.PrimitiveType;
import net.imglib2.util.Cast;

/*
 * This is autogenerated source code -- DO NOT EDIT. Instead, edit the
 * corresponding template in templates/ and rerun bin/generate.groovy.
 */


/**
 * Compute a destination X line for 2D.
 * <p>
 * An instance for a given input/output type (e.g. {@code float[]}) and {@link
 * Transform.Interpolation Interpolation} scheme can be obtained by {@link #of
 * TransformLine3D.of}.
 * <p>
 * A destination X line can then be computed by {@link #apply}, giving starting
 * position and X differential vector.
 *
 * @param <P>
 * 		input/output primitive array type (i.e., float[] or double[])
 */
@FunctionalInterface
interface VolatileTransformLine3D< P >
{

    /**
     * Compute a destination X line.
     *
     * @param src
     * 		flattened source data
     * @param dest
     * 		flattened dest data
     * @param offset
     * 		offset (into {@code dest}) of the line to compute
     * @param length
     * 		length of the line to compute (in {@code dest})
     * @param d0
     * 		partial differential vector in X of the transform (X component)
     * @param d1
     * 		partial differential vector in X of the transform (Y component)
     * @param d2
     * 		partial differential vector in X of the transform (Z component)
     * @param ss0
     * 		length of a source line (size_X)
     * @param ss1
     * 		length of a source plane (size_X * size_Y)
     * @param sf0
     * 		position of the first sample on the line (transformed into source)
     * @param sf1
     * 		position of the first sample on the line (transformed into source)
     * @param sf2
     * 		position of the first sample on the line (transformed into source)
     */
    void apply( VolatileArray< P > src, VolatileArray< P > dest, int offset, int length,
            float d0, float d1, float d2,
            int ss0, int ss1,
            float sf0, float sf1, float sf2 );

	static < P > VolatileTransformLine3D< P > of(
			final Transform.Interpolation interpolation,
			final PrimitiveType primitiveType )
	{
		if ( interpolation == Transform.Interpolation.NLINEAR )
		{
			switch ( primitiveType )
			{
			case FLOAT:
				return Cast.unchecked( NLinear_float.INSTANCE );
			case DOUBLE:
				return Cast.unchecked( NLinear_double.INSTANCE );
			default:
				throw new IllegalArgumentException();
			}
		}
		else // if ( interpolation = Transform.Interpolation.NEARESTNEIGHBOR )
		{
			switch ( primitiveType )
			{
			case BYTE:
				return Cast.unchecked( NearestNeighbor_byte.INSTANCE );
			case SHORT:
				return Cast.unchecked( NearestNeighbor_short.INSTANCE );
			case INT:
				return Cast.unchecked( NearestNeighbor_int.INSTANCE );
			case LONG:
				return Cast.unchecked( NearestNeighbor_long.INSTANCE );
			case FLOAT:
				return Cast.unchecked( NearestNeighbor_float.INSTANCE );
			case DOUBLE:
				return Cast.unchecked( NearestNeighbor_double.INSTANCE );
			default:
				throw new IllegalArgumentException();
			}
		}
	}


	// ========== NLINEAR =====================================================


	class NLinear_float implements VolatileTransformLine3D< float[] >
	{
		private NLinear_float()
		{
		}

		static final NLinear_float INSTANCE = new NLinear_float();

		@Override
		public void apply( final VolatileArray< float[] > vsrc, final VolatileArray< float[] > vdest, int offset, final int length,
		        final float d0, final float d1, final float d2,
		        final int ss0, final int ss1,
		        float sf0, float sf1, float sf2 )
		{
            final float[] srcData = vsrc.data();
            final float[] destData = vdest.data();
            final byte[] srcValid = vsrc.valid();
            final byte[] destValid = vdest.valid();

			for ( int x = 0; x < length; ++x )
			{
				final int s0 = ( int ) sf0;
				final int s1 = ( int ) sf1;
				final int s2 = ( int ) sf2;
				final float r0 = sf0 - s0;
				final float r1 = sf1 - s1;
				final float r2 = sf2 - s2;

                final int doffset = offset++;
                final int o = s2 * ss1 + s1 * ss0 + s0;

				final float a000 = srcData[ o ];
				final float a001 = srcData[ o + 1 ];
				final float a010 = srcData[ o + ss0 ];
				final float a011 = srcData[ o + ss0 + 1 ];
				final float a100 = srcData[ o + ss1 ];
				final float a101 = srcData[ o + ss1 + 1 ];
				final float a110 = srcData[ o + ss1 + ss0 ];
				final float a111 = srcData[ o + ss1 + ss0 + 1 ];
                destData[ doffset ] = a000 +
						r0 * ( -a000 + a001 ) +
						r1 * ( ( -a000 + a010 ) +
								r0 * ( a000 - a001 - a010 + a011 ) ) +
						r2 * ( ( -a000 + a100 ) +
								r0 * ( a000 - a001 - a100 + a101 ) +
								r1 * ( ( a000 - a010 - a100 + a110 ) +
										r0 * ( -a000 + a001 + a010 - a011 + a100 - a101 - a110 + a111 ) ) );

                final boolean valid = ( srcValid[ o ] != ( byte ) 0 ) &&
                        ( srcValid[ o + 1 ] != ( byte ) 0 ) &&
                        ( srcValid[ o + ss0 ] != ( byte ) 0 ) &&
                        ( srcValid[ o + ss0 + 1 ] != ( byte ) 0 ) &&
                        ( srcValid[ o + ss1 ] != ( byte ) 0 ) &&
                        ( srcValid[ o + ss1 + 1 ] != ( byte ) 0 ) &&
                        ( srcValid[ o + ss1 + ss0 ] != ( byte ) 0 ) &&
                        ( srcValid[ o + ss1 + ss0 + 1 ] != ( byte ) 0 );
                destValid[ doffset ] = valid ? ( byte ) 1 : ( byte ) 0;

				sf0 += d0;
				sf1 += d1;
				sf2 += d2;
			}
		}
	}


	class NLinear_double implements VolatileTransformLine3D< double[] >
	{
		private NLinear_double()
		{
		}

		static final NLinear_double INSTANCE = new NLinear_double();

		@Override
		public void apply( final VolatileArray< double[] > vsrc, final VolatileArray< double[] > vdest, int offset, final int length,
		        final float d0, final float d1, final float d2,
		        final int ss0, final int ss1,
		        float sf0, float sf1, float sf2 )
		{
            final double[] srcData = vsrc.data();
            final double[] destData = vdest.data();
            final byte[] srcValid = vsrc.valid();
            final byte[] destValid = vdest.valid();

			for ( int x = 0; x < length; ++x )
			{
				final int s0 = ( int ) sf0;
				final int s1 = ( int ) sf1;
				final int s2 = ( int ) sf2;
				final float r0 = sf0 - s0;
				final float r1 = sf1 - s1;
				final float r2 = sf2 - s2;

                final int doffset = offset++;
                final int o = s2 * ss1 + s1 * ss0 + s0;

				final double a000 = srcData[ o ];
				final double a001 = srcData[ o + 1 ];
				final double a010 = srcData[ o + ss0 ];
				final double a011 = srcData[ o + ss0 + 1 ];
				final double a100 = srcData[ o + ss1 ];
				final double a101 = srcData[ o + ss1 + 1 ];
				final double a110 = srcData[ o + ss1 + ss0 ];
				final double a111 = srcData[ o + ss1 + ss0 + 1 ];
                destData[ doffset ] = a000 +
						r0 * ( -a000 + a001 ) +
						r1 * ( ( -a000 + a010 ) +
								r0 * ( a000 - a001 - a010 + a011 ) ) +
						r2 * ( ( -a000 + a100 ) +
								r0 * ( a000 - a001 - a100 + a101 ) +
								r1 * ( ( a000 - a010 - a100 + a110 ) +
										r0 * ( -a000 + a001 + a010 - a011 + a100 - a101 - a110 + a111 ) ) );

                final boolean valid = ( srcValid[ o ] != ( byte ) 0 ) &&
                        ( srcValid[ o + 1 ] != ( byte ) 0 ) &&
                        ( srcValid[ o + ss0 ] != ( byte ) 0 ) &&
                        ( srcValid[ o + ss0 + 1 ] != ( byte ) 0 ) &&
                        ( srcValid[ o + ss1 ] != ( byte ) 0 ) &&
                        ( srcValid[ o + ss1 + 1 ] != ( byte ) 0 ) &&
                        ( srcValid[ o + ss1 + ss0 ] != ( byte ) 0 ) &&
                        ( srcValid[ o + ss1 + ss0 + 1 ] != ( byte ) 0 );
                destValid[ doffset ] = valid ? ( byte ) 1 : ( byte ) 0;

				sf0 += d0;
				sf1 += d1;
				sf2 += d2;
			}
		}
	}


	// ========== NEARESTNEIGHBOR =============================================


	class NearestNeighbor_float implements VolatileTransformLine3D< float[] >
	{
		private NearestNeighbor_float()
		{
		}

		static final NearestNeighbor_float INSTANCE = new NearestNeighbor_float();

		@Override
		public void apply( final VolatileArray< float[] > vsrc, final VolatileArray< float[] > vdest, int offset, final int length,
                final float d0, final float d1, final float d2,
                final int ss0, final int ss1,
                float sf0, float sf1, float sf2 )
		{
            final float[] srcData = vsrc.data();
            final float[] destData = vdest.data();
            final byte[] srcValid = vsrc.valid();
            final byte[] destValid = vdest.valid();

            sf0 += .5f;
			sf1 += .5f;
			sf2 += .5f;
			for ( int x = 0; x < length; ++x )
			{
				final int s0 = ( int ) sf0;
				final int s1 = ( int ) sf1;
				final int s2 = ( int ) sf2;
                final int doffset = offset++;
                final int soffset = s2 * ss1 + s1 * ss0 + s0;
                destData[ doffset ] = srcData[ soffset ];
                destValid[ doffset ] = srcValid[ soffset ];
				sf0 += d0;
				sf1 += d1;
				sf2 += d2;
			}
		}
	}


	class NearestNeighbor_double implements VolatileTransformLine3D< double[] >
	{
		private NearestNeighbor_double()
		{
		}

		static final NearestNeighbor_double INSTANCE = new NearestNeighbor_double();

		@Override
		public void apply( final VolatileArray< double[] > vsrc, final VolatileArray< double[] > vdest, int offset, final int length,
                final float d0, final float d1, final float d2,
                final int ss0, final int ss1,
                float sf0, float sf1, float sf2 )
		{
            final double[] srcData = vsrc.data();
            final double[] destData = vdest.data();
            final byte[] srcValid = vsrc.valid();
            final byte[] destValid = vdest.valid();

            sf0 += .5f;
			sf1 += .5f;
			sf2 += .5f;
			for ( int x = 0; x < length; ++x )
			{
				final int s0 = ( int ) sf0;
				final int s1 = ( int ) sf1;
				final int s2 = ( int ) sf2;
                final int doffset = offset++;
                final int soffset = s2 * ss1 + s1 * ss0 + s0;
                destData[ doffset ] = srcData[ soffset ];
                destValid[ doffset ] = srcValid[ soffset ];
				sf0 += d0;
				sf1 += d1;
				sf2 += d2;
			}
		}
	}


	class NearestNeighbor_byte implements VolatileTransformLine3D< byte[] >
	{
		private NearestNeighbor_byte()
		{
		}

		static final NearestNeighbor_byte INSTANCE = new NearestNeighbor_byte();

		@Override
		public void apply( final VolatileArray< byte[] > vsrc, final VolatileArray< byte[] > vdest, int offset, final int length,
                final float d0, final float d1, final float d2,
                final int ss0, final int ss1,
                float sf0, float sf1, float sf2 )
		{
            final byte[] srcData = vsrc.data();
            final byte[] destData = vdest.data();
            final byte[] srcValid = vsrc.valid();
            final byte[] destValid = vdest.valid();

            sf0 += .5f;
			sf1 += .5f;
			sf2 += .5f;
			for ( int x = 0; x < length; ++x )
			{
				final int s0 = ( int ) sf0;
				final int s1 = ( int ) sf1;
				final int s2 = ( int ) sf2;
                final int doffset = offset++;
                final int soffset = s2 * ss1 + s1 * ss0 + s0;
                destData[ doffset ] = srcData[ soffset ];
                destValid[ doffset ] = srcValid[ soffset ];
				sf0 += d0;
				sf1 += d1;
				sf2 += d2;
			}
		}
	}


	class NearestNeighbor_short implements VolatileTransformLine3D< short[] >
	{
		private NearestNeighbor_short()
		{
		}

		static final NearestNeighbor_short INSTANCE = new NearestNeighbor_short();

		@Override
		public void apply( final VolatileArray< short[] > vsrc, final VolatileArray< short[] > vdest, int offset, final int length,
                final float d0, final float d1, final float d2,
                final int ss0, final int ss1,
                float sf0, float sf1, float sf2 )
		{
            final short[] srcData = vsrc.data();
            final short[] destData = vdest.data();
            final byte[] srcValid = vsrc.valid();
            final byte[] destValid = vdest.valid();

            sf0 += .5f;
			sf1 += .5f;
			sf2 += .5f;
			for ( int x = 0; x < length; ++x )
			{
				final int s0 = ( int ) sf0;
				final int s1 = ( int ) sf1;
				final int s2 = ( int ) sf2;
                final int doffset = offset++;
                final int soffset = s2 * ss1 + s1 * ss0 + s0;
                destData[ doffset ] = srcData[ soffset ];
                destValid[ doffset ] = srcValid[ soffset ];
				sf0 += d0;
				sf1 += d1;
				sf2 += d2;
			}
		}
	}


	class NearestNeighbor_int implements VolatileTransformLine3D< int[] >
	{
		private NearestNeighbor_int()
		{
		}

		static final NearestNeighbor_int INSTANCE = new NearestNeighbor_int();

		@Override
		public void apply( final VolatileArray< int[] > vsrc, final VolatileArray< int[] > vdest, int offset, final int length,
                final float d0, final float d1, final float d2,
                final int ss0, final int ss1,
                float sf0, float sf1, float sf2 )
		{
            final int[] srcData = vsrc.data();
            final int[] destData = vdest.data();
            final byte[] srcValid = vsrc.valid();
            final byte[] destValid = vdest.valid();

            sf0 += .5f;
			sf1 += .5f;
			sf2 += .5f;
			for ( int x = 0; x < length; ++x )
			{
				final int s0 = ( int ) sf0;
				final int s1 = ( int ) sf1;
				final int s2 = ( int ) sf2;
                final int doffset = offset++;
                final int soffset = s2 * ss1 + s1 * ss0 + s0;
                destData[ doffset ] = srcData[ soffset ];
                destValid[ doffset ] = srcValid[ soffset ];
				sf0 += d0;
				sf1 += d1;
				sf2 += d2;
			}
		}
	}


	class NearestNeighbor_long implements VolatileTransformLine3D< long[] >
	{
		private NearestNeighbor_long()
		{
		}

		static final NearestNeighbor_long INSTANCE = new NearestNeighbor_long();

		@Override
		public void apply( final VolatileArray< long[] > vsrc, final VolatileArray< long[] > vdest, int offset, final int length,
                final float d0, final float d1, final float d2,
                final int ss0, final int ss1,
                float sf0, float sf1, float sf2 )
		{
            final long[] srcData = vsrc.data();
            final long[] destData = vdest.data();
            final byte[] srcValid = vsrc.valid();
            final byte[] destValid = vdest.valid();

            sf0 += .5f;
			sf1 += .5f;
			sf2 += .5f;
			for ( int x = 0; x < length; ++x )
			{
				final int s0 = ( int ) sf0;
				final int s1 = ( int ) sf1;
				final int s2 = ( int ) sf2;
                final int doffset = offset++;
                final int soffset = s2 * ss1 + s1 * ss0 + s0;
                destData[ doffset ] = srcData[ soffset ];
                destValid[ doffset ] = srcValid[ soffset ];
				sf0 += d0;
				sf1 += d1;
				sf2 += d2;
			}
		}
	}
}
