package net.imglib2.algorithm.blocks.dfield;

import net.imglib2.algorithm.blocks.transform.Transform;
import net.imglib2.type.PrimitiveType;
import net.imglib2.util.Cast;

/*
 * This is autogenerated source code -- DO NOT EDIT. Instead, edit the
 * corresponding template in templates/ and rerun bin/generate.groovy.
 */


/**
 * TODO javadoc
 *
 * @param <F>
 * 		displacement field primitive array type (float[] or double[])
 * @param <P>
 * 		input/output primitive array type (e.g., byte[] or float[])
 */
@FunctionalInterface
interface Lookup2D< F, P >
{
	/**
	 * TODO javadoc
	 * <p>
	 * The dimensions of {@code pfield} match the dimensions of {@code dest}.
	 * (But {@code pfield} has 2 displacement vector components for every {@code
	 * dest} element, so there are {@code length} elements in {@code dest} to
	 * fill, and {@code 2*length} elements in {@code pfield}.)
	 * <p>
	 * The offsets {@code d0, d1} account for (scaled) offset of both the
	 * displacement field block and the src block. They should be computed like
	 * this:
	 * <pre>{@code
	 * d0 = displacementScale0 * fieldTransform.sourcePos[1] + displacementOffset0 - lookupTransform.sourcePos[0]
	 * d1 = displacementScale1 * fieldTransform.sourcePos[2] + displacementOffset1 - lookupTransform.sourcePos[1]
	 * }</pre>
	 *
	 * @param pfield
	 * 		flattened position field data
	 * @param d0
	 * 		X offset to apply to {@code pfield} vectors
	 * @param d1
	 * 		Y offset to apply to {@code pfield} vectors
	 * @param src
	 * 		flattened source data
	 * @param dest
	 * 		flattened dest data
	 * @param length
	 * 		number of {@code dest} elements to compute
	 * @param ss0
	 * 		length of a source line (size_X)
	 */
	void apply( F pfield, double d0, double d1, P src, P dest, int length, int ss0 );


	static < F, P > Lookup2D< F, P > of(
			final PrimitiveType dfieldPrimitiveType,
			final Transform.Interpolation interpolation,
			final PrimitiveType primitiveType )
	{
		switch ( dfieldPrimitiveType )
		{
		case FLOAT:
			if ( interpolation == Transform.Interpolation.NLINEAR )
			{
				switch ( primitiveType )
				{
				case FLOAT:
					// TODO
				case DOUBLE:
					// TODO
					throw new UnsupportedOperationException( "TODO. not implemented" );
				default:
					throw new IllegalArgumentException();
				}
			}
			else // if ( interpolation = Transform.Interpolation.NEARESTNEIGHBOR )
			{
				switch ( primitiveType )
				{
				case BYTE:
					// TODO
				case SHORT:
					// TODO
				case INT:
					// TODO
				case LONG:
					// TODO
				case FLOAT:
					// TODO
				case DOUBLE:
					// TODO
					throw new UnsupportedOperationException( "TODO. not implemented" );
				default:
					throw new IllegalArgumentException();
				}
			}
		case DOUBLE:
			if ( interpolation == Transform.Interpolation.NLINEAR )
			{
				switch ( primitiveType )
				{
				case FLOAT:
					// TODO
				case DOUBLE:
					// TODO
					throw new UnsupportedOperationException( "TODO. not implemented" );
				default:
					throw new IllegalArgumentException();
				}
			}
			else // if ( interpolation = Transform.Interpolation.NEARESTNEIGHBOR )
			{
				switch ( primitiveType )
				{
				case BYTE:
					return Cast.unchecked( NearestNeighbor_doubleField_byte.INSTANCE );
				case SHORT:
					// TODO
				case INT:
					// TODO
				case LONG:
					// TODO
				case FLOAT:
					// TODO
				case DOUBLE:
					// TODO
					throw new UnsupportedOperationException( "TODO. not implemented" );
				default:
					throw new IllegalArgumentException();
				}
			}
		default:
			throw new IllegalArgumentException();
		}
	}


	// ========== NLINEAR =====================================================


	// TODO
	// TODO
	// TODO
	// TODO


	// ========== NEARESTNEIGHBOR =============================================


	class NearestNeighbor_doubleField_byte implements Lookup2D< double[], byte[] >
	{
		private NearestNeighbor_doubleField_byte()
		{
		}

		static final NearestNeighbor_doubleField_byte INSTANCE = new NearestNeighbor_doubleField_byte();

		@Override
		public void apply( final double[] pfield,
				double d0, double d1,
				final byte[] src, final byte[] dest, final int length,
				final int ss0 )
		{
			d0 += .5; // +.5 for nearest-neighbor rounding
			d1 += .5;
			for ( int x = 0; x < length; ++x )
			{
				final double p0 = pfield[ 2 * x ];
				final double p1 = pfield[ 2 * x + 1 ];
				final int s0 = ( int ) ( p0 + d0 );
				final int s1 = ( int ) ( p1 + d1 );
				dest[ x ] = src[ s1 * ss0 + s0 ];
			}
		}
	}

	// TODO
	// TODO
	// TODO
	// TODO

}
