/*
 * #%L
 * ImgLib2: a general-purpose, multidimensional image processing library.
 * %%
 * Copyright (C) 2009 - 2025 Tobias Pietzsch, Stephan Preibisch, Stephan Saalfeld,
 * John Bogovic, Albert Cardona, Barry DeZonia, Christian Dietz, Jan Funke,
 * Aivar Grislis, Jonathan Hale, Grant Harris, Stefan Helfrich, Mark Hiner,
 * Martin Horn, Steffen Jaensch, Lee Kamentsky, Larry Lindsey, Melissa Linkert,
 * Mark Longair, Brian Northan, Nick Perry, Curtis Rueden, Johannes Schindelin,
 * Jean-Yves Tinevez and Michael Zinsmaier.
 * %%
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 * #L%
 */
package net.imglib2.algorithm.blocks.dfield;

import net.imglib2.algorithm.blocks.transform.Transform;
import net.imglib2.type.PrimitiveType;
import net.imglib2.util.Cast;

/*
 * This is autogenerated source code -- DO NOT EDIT. Instead, edit the
 * corresponding template in templates/ and rerun bin/generate.groovy.
 */


/**
 * TODO javadoc
 *
 * @param <F>
 * 		displacement field primitive array type (float[] or double[])
 * @param <P>
 * 		input/output primitive array type (e.g., byte[] or float[])
 */
@FunctionalInterface
interface Lookup2D< F, P >
{
	/**
	 * TODO javadoc
	 * <p>
	 * The dimensions of {@code pfield} match the dimensions of {@code dest}.
	 * (But {@code pfield} has 2 displacement vector components for every {@code
	 * dest} element, so there are {@code length} elements in {@code dest} to
	 * fill, and {@code 2*length} elements in {@code pfield}.)
	 * <p>
	 * The offsets {@code d0, d1} account for (scaled) offset of both the
	 * displacement field block and the src block. They should be computed like
	 * this:
	 * <pre>{@code
	 * d0 = displacementScale0 * fieldTransform.sourcePos[1] + displacementOffset0 - lookupTransform.sourcePos[0]
	 * d1 = displacementScale1 * fieldTransform.sourcePos[2] + displacementOffset1 - lookupTransform.sourcePos[1]
	 * }</pre>
	 *
	 * @param pfield
	 * 		flattened position field data
	 * @param d0
	 * 		X offset to apply to {@code pfield} vectors
	 * @param d1
	 * 		Y offset to apply to {@code pfield} vectors
	 * @param src
	 * 		flattened source data
	 * @param dest
	 * 		flattened dest data
	 * @param length
	 * 		number of {@code dest} elements to compute
	 * @param ss0
	 * 		length of a source line (size_X)
	 */
	void apply( F pfield, double d0, double d1, P src, P dest, int length, int ss0 );


	static < F, P > Lookup2D< F, P > of(
			final PrimitiveType dfieldPrimitiveType,
			final Transform.Interpolation interpolation,
			final PrimitiveType primitiveType )
	{
		switch ( dfieldPrimitiveType )
		{
		case FLOAT:
			if ( interpolation == Transform.Interpolation.NLINEAR )
			{
				switch ( primitiveType )
				{
				case FLOAT:
					return Cast.unchecked( NLinear_floatField_float.INSTANCE );
				case DOUBLE:
					return Cast.unchecked( NLinear_floatField_double.INSTANCE );
				default:
					throw new IllegalArgumentException();
				}
			}
			else // if ( interpolation = Transform.Interpolation.NEARESTNEIGHBOR )
			{
				switch ( primitiveType )
				{
				case BYTE:
					return Cast.unchecked( NearestNeighbor_floatField_byte.INSTANCE );
				case SHORT:
					return Cast.unchecked( NearestNeighbor_floatField_short.INSTANCE );
				case INT:
					return Cast.unchecked( NearestNeighbor_floatField_int.INSTANCE );
				case LONG:
					return Cast.unchecked( NearestNeighbor_floatField_long.INSTANCE );
				case FLOAT:
					return Cast.unchecked( NearestNeighbor_floatField_float.INSTANCE );
				case DOUBLE:
					return Cast.unchecked( NearestNeighbor_floatField_double.INSTANCE );
				default:
					throw new IllegalArgumentException();
				}
			}
		case DOUBLE:
			if ( interpolation == Transform.Interpolation.NLINEAR )
			{
				switch ( primitiveType )
				{
				case FLOAT:
					return Cast.unchecked( NLinear_doubleField_float.INSTANCE );
				case DOUBLE:
					return Cast.unchecked( NLinear_doubleField_double.INSTANCE );
				default:
					throw new IllegalArgumentException();
				}
			}
			else // if ( interpolation = Transform.Interpolation.NEARESTNEIGHBOR )
			{
				switch ( primitiveType )
				{
				case BYTE:
					return Cast.unchecked( NearestNeighbor_doubleField_byte.INSTANCE );
				case SHORT:
					return Cast.unchecked( NearestNeighbor_doubleField_short.INSTANCE );
				case INT:
					return Cast.unchecked( NearestNeighbor_doubleField_int.INSTANCE );
				case LONG:
					return Cast.unchecked( NearestNeighbor_doubleField_long.INSTANCE );
				case FLOAT:
					return Cast.unchecked( NearestNeighbor_doubleField_float.INSTANCE );
				case DOUBLE:
					return Cast.unchecked( NearestNeighbor_doubleField_double.INSTANCE );
				default:
					throw new IllegalArgumentException();
				}
			}
		default:
			throw new IllegalArgumentException();
		}
	}


	// ========== NLINEAR =====================================================


	class NLinear_floatField_float implements Lookup2D< float[], float[] >
	{
		private NLinear_floatField_float()
		{
		}

		static final NLinear_floatField_float INSTANCE = new NLinear_floatField_float();

		@Override
		public void apply( final float[] pfield,
				double d0, double d1,
				final float[] src, final float[] dest, final int length,
				final int ss0 )
		{
			for ( int x = 0; x < length; ++x )
			{
				final float sf0 = pfield[ 2 * x ] + (float) d0;
				final float sf1 = pfield[ 2 * x + 1 ] + (float) d1;
				final int s0 = ( int ) sf0;
				final int s1 = ( int ) sf1;
				final float r0 = ( float ) ( sf0 - s0 );
				final float r1 = ( float ) ( sf1 - s1 );
				final int o = s1 * ss0 + s0;
				final float a00 = src[ o ];
				final float a01 = src[ o + 1 ];
				final float a10 = src[ o + ss0 ];
				final float a11 = src[ o + ss0 + 1 ];
				dest[ x ] = a00 + r0 * ( a01 - a00 ) + r1 * ( a10 - a00 + r0 * ( a00 - a10 - a01 + a11 ) );
			}
		}
	}


	class NLinear_floatField_double implements Lookup2D< float[], double[] >
	{
		private NLinear_floatField_double()
		{
		}

		static final NLinear_floatField_double INSTANCE = new NLinear_floatField_double();

		@Override
		public void apply( final float[] pfield,
				double d0, double d1,
				final double[] src, final double[] dest, final int length,
				final int ss0 )
		{
			for ( int x = 0; x < length; ++x )
			{
				final float sf0 = pfield[ 2 * x ] + (float) d0;
				final float sf1 = pfield[ 2 * x + 1 ] + (float) d1;
				final int s0 = ( int ) sf0;
				final int s1 = ( int ) sf1;
				final float r0 = ( float ) ( sf0 - s0 );
				final float r1 = ( float ) ( sf1 - s1 );
				final int o = s1 * ss0 + s0;
				final double a00 = src[ o ];
				final double a01 = src[ o + 1 ];
				final double a10 = src[ o + ss0 ];
				final double a11 = src[ o + ss0 + 1 ];
				dest[ x ] = a00 + r0 * ( a01 - a00 ) + r1 * ( a10 - a00 + r0 * ( a00 - a10 - a01 + a11 ) );
			}
		}
	}


	class NLinear_doubleField_float implements Lookup2D< double[], float[] >
	{
		private NLinear_doubleField_float()
		{
		}

		static final NLinear_doubleField_float INSTANCE = new NLinear_doubleField_float();

		@Override
		public void apply( final double[] pfield,
				double d0, double d1,
				final float[] src, final float[] dest, final int length,
				final int ss0 )
		{
			for ( int x = 0; x < length; ++x )
			{
				final double sf0 = pfield[ 2 * x ] + (double) d0;
				final double sf1 = pfield[ 2 * x + 1 ] + (double) d1;
				final int s0 = ( int ) sf0;
				final int s1 = ( int ) sf1;
				final float r0 = ( float ) ( sf0 - s0 );
				final float r1 = ( float ) ( sf1 - s1 );
				final int o = s1 * ss0 + s0;
				final float a00 = src[ o ];
				final float a01 = src[ o + 1 ];
				final float a10 = src[ o + ss0 ];
				final float a11 = src[ o + ss0 + 1 ];
				dest[ x ] = a00 + r0 * ( a01 - a00 ) + r1 * ( a10 - a00 + r0 * ( a00 - a10 - a01 + a11 ) );
			}
		}
	}


	class NLinear_doubleField_double implements Lookup2D< double[], double[] >
	{
		private NLinear_doubleField_double()
		{
		}

		static final NLinear_doubleField_double INSTANCE = new NLinear_doubleField_double();

		@Override
		public void apply( final double[] pfield,
				double d0, double d1,
				final double[] src, final double[] dest, final int length,
				final int ss0 )
		{
			for ( int x = 0; x < length; ++x )
			{
				final double sf0 = pfield[ 2 * x ] + (double) d0;
				final double sf1 = pfield[ 2 * x + 1 ] + (double) d1;
				final int s0 = ( int ) sf0;
				final int s1 = ( int ) sf1;
				final float r0 = ( float ) ( sf0 - s0 );
				final float r1 = ( float ) ( sf1 - s1 );
				final int o = s1 * ss0 + s0;
				final double a00 = src[ o ];
				final double a01 = src[ o + 1 ];
				final double a10 = src[ o + ss0 ];
				final double a11 = src[ o + ss0 + 1 ];
				dest[ x ] = a00 + r0 * ( a01 - a00 ) + r1 * ( a10 - a00 + r0 * ( a00 - a10 - a01 + a11 ) );
			}
		}
	}


	// ========== NEARESTNEIGHBOR =============================================


	class NearestNeighbor_floatField_float implements Lookup2D< float[], float[] >
	{
		private NearestNeighbor_floatField_float()
		{
		}

		static final NearestNeighbor_floatField_float INSTANCE = new NearestNeighbor_floatField_float();

		@Override
		public void apply( final float[] pfield,
				double d0, double d1,
				final float[] src, final float[] dest, final int length,
				final int ss0 )
		{
			d0 += .5; // +.5 for nearest-neighbor rounding
			d1 += .5;
			for ( int x = 0; x < length; ++x )
			{
				final float sf0 = pfield[ 2 * x ] + (float) d0;
				final float sf1 = pfield[ 2 * x + 1 ] + (float) d1;
				final int s0 = ( int ) sf0;
				final int s1 = ( int ) sf1;
				dest[ x ] = src[ s1 * ss0 + s0 ];
			}
		}
	}


	class NearestNeighbor_floatField_double implements Lookup2D< float[], double[] >
	{
		private NearestNeighbor_floatField_double()
		{
		}

		static final NearestNeighbor_floatField_double INSTANCE = new NearestNeighbor_floatField_double();

		@Override
		public void apply( final float[] pfield,
				double d0, double d1,
				final double[] src, final double[] dest, final int length,
				final int ss0 )
		{
			d0 += .5; // +.5 for nearest-neighbor rounding
			d1 += .5;
			for ( int x = 0; x < length; ++x )
			{
				final float sf0 = pfield[ 2 * x ] + (float) d0;
				final float sf1 = pfield[ 2 * x + 1 ] + (float) d1;
				final int s0 = ( int ) sf0;
				final int s1 = ( int ) sf1;
				dest[ x ] = src[ s1 * ss0 + s0 ];
			}
		}
	}


	class NearestNeighbor_floatField_byte implements Lookup2D< float[], byte[] >
	{
		private NearestNeighbor_floatField_byte()
		{
		}

		static final NearestNeighbor_floatField_byte INSTANCE = new NearestNeighbor_floatField_byte();

		@Override
		public void apply( final float[] pfield,
				double d0, double d1,
				final byte[] src, final byte[] dest, final int length,
				final int ss0 )
		{
			d0 += .5; // +.5 for nearest-neighbor rounding
			d1 += .5;
			for ( int x = 0; x < length; ++x )
			{
				final float sf0 = pfield[ 2 * x ] + (float) d0;
				final float sf1 = pfield[ 2 * x + 1 ] + (float) d1;
				final int s0 = ( int ) sf0;
				final int s1 = ( int ) sf1;
				dest[ x ] = src[ s1 * ss0 + s0 ];
			}
		}
	}


	class NearestNeighbor_floatField_short implements Lookup2D< float[], short[] >
	{
		private NearestNeighbor_floatField_short()
		{
		}

		static final NearestNeighbor_floatField_short INSTANCE = new NearestNeighbor_floatField_short();

		@Override
		public void apply( final float[] pfield,
				double d0, double d1,
				final short[] src, final short[] dest, final int length,
				final int ss0 )
		{
			d0 += .5; // +.5 for nearest-neighbor rounding
			d1 += .5;
			for ( int x = 0; x < length; ++x )
			{
				final float sf0 = pfield[ 2 * x ] + (float) d0;
				final float sf1 = pfield[ 2 * x + 1 ] + (float) d1;
				final int s0 = ( int ) sf0;
				final int s1 = ( int ) sf1;
				dest[ x ] = src[ s1 * ss0 + s0 ];
			}
		}
	}


	class NearestNeighbor_floatField_int implements Lookup2D< float[], int[] >
	{
		private NearestNeighbor_floatField_int()
		{
		}

		static final NearestNeighbor_floatField_int INSTANCE = new NearestNeighbor_floatField_int();

		@Override
		public void apply( final float[] pfield,
				double d0, double d1,
				final int[] src, final int[] dest, final int length,
				final int ss0 )
		{
			d0 += .5; // +.5 for nearest-neighbor rounding
			d1 += .5;
			for ( int x = 0; x < length; ++x )
			{
				final float sf0 = pfield[ 2 * x ] + (float) d0;
				final float sf1 = pfield[ 2 * x + 1 ] + (float) d1;
				final int s0 = ( int ) sf0;
				final int s1 = ( int ) sf1;
				dest[ x ] = src[ s1 * ss0 + s0 ];
			}
		}
	}


	class NearestNeighbor_floatField_long implements Lookup2D< float[], long[] >
	{
		private NearestNeighbor_floatField_long()
		{
		}

		static final NearestNeighbor_floatField_long INSTANCE = new NearestNeighbor_floatField_long();

		@Override
		public void apply( final float[] pfield,
				double d0, double d1,
				final long[] src, final long[] dest, final int length,
				final int ss0 )
		{
			d0 += .5; // +.5 for nearest-neighbor rounding
			d1 += .5;
			for ( int x = 0; x < length; ++x )
			{
				final float sf0 = pfield[ 2 * x ] + (float) d0;
				final float sf1 = pfield[ 2 * x + 1 ] + (float) d1;
				final int s0 = ( int ) sf0;
				final int s1 = ( int ) sf1;
				dest[ x ] = src[ s1 * ss0 + s0 ];
			}
		}
	}


	class NearestNeighbor_doubleField_float implements Lookup2D< double[], float[] >
	{
		private NearestNeighbor_doubleField_float()
		{
		}

		static final NearestNeighbor_doubleField_float INSTANCE = new NearestNeighbor_doubleField_float();

		@Override
		public void apply( final double[] pfield,
				double d0, double d1,
				final float[] src, final float[] dest, final int length,
				final int ss0 )
		{
			d0 += .5; // +.5 for nearest-neighbor rounding
			d1 += .5;
			for ( int x = 0; x < length; ++x )
			{
				final double sf0 = pfield[ 2 * x ] + (double) d0;
				final double sf1 = pfield[ 2 * x + 1 ] + (double) d1;
				final int s0 = ( int ) sf0;
				final int s1 = ( int ) sf1;
				dest[ x ] = src[ s1 * ss0 + s0 ];
			}
		}
	}


	class NearestNeighbor_doubleField_double implements Lookup2D< double[], double[] >
	{
		private NearestNeighbor_doubleField_double()
		{
		}

		static final NearestNeighbor_doubleField_double INSTANCE = new NearestNeighbor_doubleField_double();

		@Override
		public void apply( final double[] pfield,
				double d0, double d1,
				final double[] src, final double[] dest, final int length,
				final int ss0 )
		{
			d0 += .5; // +.5 for nearest-neighbor rounding
			d1 += .5;
			for ( int x = 0; x < length; ++x )
			{
				final double sf0 = pfield[ 2 * x ] + (double) d0;
				final double sf1 = pfield[ 2 * x + 1 ] + (double) d1;
				final int s0 = ( int ) sf0;
				final int s1 = ( int ) sf1;
				dest[ x ] = src[ s1 * ss0 + s0 ];
			}
		}
	}


	class NearestNeighbor_doubleField_byte implements Lookup2D< double[], byte[] >
	{
		private NearestNeighbor_doubleField_byte()
		{
		}

		static final NearestNeighbor_doubleField_byte INSTANCE = new NearestNeighbor_doubleField_byte();

		@Override
		public void apply( final double[] pfield,
				double d0, double d1,
				final byte[] src, final byte[] dest, final int length,
				final int ss0 )
		{
			d0 += .5; // +.5 for nearest-neighbor rounding
			d1 += .5;
			for ( int x = 0; x < length; ++x )
			{
				final double sf0 = pfield[ 2 * x ] + (double) d0;
				final double sf1 = pfield[ 2 * x + 1 ] + (double) d1;
				final int s0 = ( int ) sf0;
				final int s1 = ( int ) sf1;
				dest[ x ] = src[ s1 * ss0 + s0 ];
			}
		}
	}


	class NearestNeighbor_doubleField_short implements Lookup2D< double[], short[] >
	{
		private NearestNeighbor_doubleField_short()
		{
		}

		static final NearestNeighbor_doubleField_short INSTANCE = new NearestNeighbor_doubleField_short();

		@Override
		public void apply( final double[] pfield,
				double d0, double d1,
				final short[] src, final short[] dest, final int length,
				final int ss0 )
		{
			d0 += .5; // +.5 for nearest-neighbor rounding
			d1 += .5;
			for ( int x = 0; x < length; ++x )
			{
				final double sf0 = pfield[ 2 * x ] + (double) d0;
				final double sf1 = pfield[ 2 * x + 1 ] + (double) d1;
				final int s0 = ( int ) sf0;
				final int s1 = ( int ) sf1;
				dest[ x ] = src[ s1 * ss0 + s0 ];
			}
		}
	}


	class NearestNeighbor_doubleField_int implements Lookup2D< double[], int[] >
	{
		private NearestNeighbor_doubleField_int()
		{
		}

		static final NearestNeighbor_doubleField_int INSTANCE = new NearestNeighbor_doubleField_int();

		@Override
		public void apply( final double[] pfield,
				double d0, double d1,
				final int[] src, final int[] dest, final int length,
				final int ss0 )
		{
			d0 += .5; // +.5 for nearest-neighbor rounding
			d1 += .5;
			for ( int x = 0; x < length; ++x )
			{
				final double sf0 = pfield[ 2 * x ] + (double) d0;
				final double sf1 = pfield[ 2 * x + 1 ] + (double) d1;
				final int s0 = ( int ) sf0;
				final int s1 = ( int ) sf1;
				dest[ x ] = src[ s1 * ss0 + s0 ];
			}
		}
	}


	class NearestNeighbor_doubleField_long implements Lookup2D< double[], long[] >
	{
		private NearestNeighbor_doubleField_long()
		{
		}

		static final NearestNeighbor_doubleField_long INSTANCE = new NearestNeighbor_doubleField_long();

		@Override
		public void apply( final double[] pfield,
				double d0, double d1,
				final long[] src, final long[] dest, final int length,
				final int ss0 )
		{
			d0 += .5; // +.5 for nearest-neighbor rounding
			d1 += .5;
			for ( int x = 0; x < length; ++x )
			{
				final double sf0 = pfield[ 2 * x ] + (double) d0;
				final double sf1 = pfield[ 2 * x + 1 ] + (double) d1;
				final int s0 = ( int ) sf0;
				final int s1 = ( int ) sf1;
				dest[ x ] = src[ s1 * ss0 + s0 ];
			}
		}
	}
}
